# Form implementation generated from reading ui file 'app/modules/main_window/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 900)
        MainWindow.setStyleSheet("\n"
"    /* Tổng thể hệ thống */\n"
"    QMainWindow {\n"
"        background-color: #f8fafc;\n"
"    }\n"
"\n"
"    /* Sidebar Side - Modern Enterprise Design với Gradient nền */\n"
"    QFrame#frame_sidebar {\n"
"        /* Chuyển sắc từ Trắng (trên) xuống Xám Xanh đậm dần (dưới) */\n"
"        background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                    stop:0 #ffffff, stop:1 #cbd5e1);\n"
"        border-right: 1px solid #e1e7ef;\n"
"        min-width: 280px;\n"
"        max-width: 280px;\n"
"        /* Thêm shadow để hiện đại hơn */\n"
"        box-shadow: 2px 0 8px rgba(0, 0, 0, 0.1);\n"
"    }\n"
"\n"
"    /* Header Logo Area - Gradient và Modern */\n"
"    QLabel#lbl_logo {\n"
"        color: #ffffff;\n"
"        font-size: 20px;\n"
"        font-weight: 700;\n"
"        padding: 20px;\n"
"        background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                    stop:0 #4f46e5, stop:1 #7c3aed);\n"
"        /* Gradient xanh tím enterprise */\n"
"        border-bottom: 1px solid #e1e7ef;\n"
"    }\n"
"\n"
"    /* List Menu Điều hướng - Cải tiến với border-radius và spacing */\n"
"    QListWidget#sidebar_menu {\n"
"        background-color: transparent;\n"
"        border: none;\n"
"        outline: none;\n"
"        padding-top: 20px;\n"
"        padding-bottom: 20px;\n"
"    }\n"
"    QListWidget#sidebar_menu::item {\n"
"        color: #374151;\n"
"        padding: 16px 24px;\n"
"        border-left: 4px solid transparent;\n"
"        font-size: 14px;\n"
"        font-weight: 500;\n"
"        border-radius: 8px;\n"
"        /* Thêm bo góc hiện đại */\n"
"        margin: 4px 12px;\n"
"        /* Tăng margin để không chạm viền */\n"
"    }\n"
"    QListWidget#sidebar_menu::item:hover {\n"
"        background-color: #f3f4f6;\n"
"        color: #1f2937;\n"
"        border-radius: 8px;\n"
"    }\n"
"    QListWidget#sidebar_menu::item:selected {\n"
"        background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                    stop:0 #dbeafe, stop:1 #bfdbfe);\n"
"        /* Gradient xanh nhạt */\n"
"        color: #1e40af;\n"
"        border-left: 4px solid #3b82f6;\n"
"        font-weight: 600;\n"
"        border-radius: 8px;\n"
"    }\n"
"\n"
"    /* Scrollbar cho QListWidget - Làm thanh cuộn đẹp hơn và dài hơn */\n"
"    QListWidget#sidebar_menu QScrollBar:vertical {\n"
"        background: transparent;\n"
"        width: 8px;\n"
"        border-radius: 4px;\n"
"    }\n"
"    QListWidget#sidebar_menu QScrollBar::handle:vertical {\n"
"        background: #cbd5e1;\n"
"        border-radius: 4px;\n"
"        min-height: 40px; /* Tăng min-height để thanh cuộn dài hơn */\n"
"    }\n"
"    QListWidget#sidebar_menu QScrollBar::handle:vertical:hover {\n"
"        background: #94a3b8;\n"
"    }\n"
"    QListWidget#sidebar_menu QScrollBar::add-line:vertical,\n"
"    QListWidget#sidebar_menu QScrollBar::sub-line:vertical {\n"
"        border: none;\n"
"        background: none;\n"
"    }\n"
"\n"
"    /* Vùng hiển thị nội dung bên phải */\n"
"    QStackedWidget#content_stack {\n"
"        background-color: #f8fafc;\n"
"    }\n"
"\n"
"    /* Footer Sidebar */\n"
"    QLabel#lbl_version {\n"
"        color: #9ca3af;\n"
"        font-size: 11px;\n"
"        padding: 16px;\n"
"        background-color: transparent;\n"
"        border-top: 1px solid #e5e7eb;\n"
"    }\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_main = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_main.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_main.setSpacing(0)
        self.horizontalLayout_main.setObjectName("horizontalLayout_main")
        self.frame_sidebar = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_sidebar.setObjectName("frame_sidebar")
        self.verticalLayout_sidebar = QtWidgets.QVBoxLayout(self.frame_sidebar)
        self.verticalLayout_sidebar.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_sidebar.setSpacing(0)
        self.verticalLayout_sidebar.setObjectName("verticalLayout_sidebar")
        self.lbl_logo = QtWidgets.QLabel(parent=self.frame_sidebar)
        self.lbl_logo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_logo.setObjectName("lbl_logo")
        self.verticalLayout_sidebar.addWidget(self.lbl_logo)
        self.sidebar_menu = QtWidgets.QListWidget(parent=self.frame_sidebar)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.sidebar_menu.setFont(font)
        self.sidebar_menu.setObjectName("sidebar_menu")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(17)
        item.setFont(font)
        self.sidebar_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(17)
        item.setFont(font)
        self.sidebar_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(17)
        item.setFont(font)
        self.sidebar_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(17)
        item.setFont(font)
        self.sidebar_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(17)
        item.setFont(font)
        self.sidebar_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(17)
        item.setFont(font)
        self.sidebar_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(17)
        item.setFont(font)
        self.sidebar_menu.addItem(item)
        self.verticalLayout_sidebar.addWidget(self.sidebar_menu)
        self.horizontalLayout_main.addWidget(self.frame_sidebar)
        self.content_stack = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.content_stack.setObjectName("content_stack")
        self.horizontalLayout_main.addWidget(self.content_stack)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.content_stack.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "POS MINI - Hệ thống Quản lý VPP Enterprise"))
        self.lbl_logo.setText(_translate("MainWindow", "POS MINI"))
        __sortingEnabled = self.sidebar_menu.isSortingEnabled()
        self.sidebar_menu.setSortingEnabled(False)
        item = self.sidebar_menu.item(0)
        item.setText(_translate("MainWindow", "🏠  Trang chủ"))
        item = self.sidebar_menu.item(1)
        item.setText(_translate("MainWindow", "🏷️  Quản lý sản phẩm"))
        item = self.sidebar_menu.item(2)
        item.setText(_translate("MainWindow", "📦  Quản lý kho"))
        item = self.sidebar_menu.item(3)
        item.setText(_translate("MainWindow", "🛒  Bán hàng"))
        item = self.sidebar_menu.item(4)
        item.setText(_translate("MainWindow", "📊  Báo cáo và thống kê"))
        item = self.sidebar_menu.item(5)
        item.setText(_translate("MainWindow", "🧾  Quản lý thuế"))
        item = self.sidebar_menu.item(6)
        item.setText(_translate("MainWindow", "⚙️  Cấu hình hệ thống"))
        self.sidebar_menu.setSortingEnabled(__sortingEnabled)
